# Generated by Django 4.0.3 on 2022-05-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='salary_log',
            field=models.TextField(default=''),
        ),
    ]
