# Generated by Django 4.0.3 on 2022-06-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userinfo_salary_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='batch_log',
            field=models.TextField(default="{'TaskID': {}, 'Time': {}, 'BatchSize': {}}"),
        ),
    ]
