# Generated by Django 4.0.3 on 2022-06-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userinfo_batch_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='batch_log',
            field=models.TextField(default="{'TaskID': {}, 'TaskName': {}, 'DataType': {}, 'LastTime': {}, 'TaskState': {}}"),
        ),
    ]
