# Generated by Django 4.0.3 on 2022-06-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_userinfo_batch_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='batch_log',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='salary_log',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='label_log',
            field=models.TextField(default="{'TaskID': {}, 'TaskName': {}, 'ItemID': {}, 'Time': {}, 'State': {}}"),
        ),
    ]
