# Generated by Django 4.0.3 on 2022-06-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_userinfo_batch_log_remove_userinfo_salary_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='label_log',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='salary_log',
            field=models.TextField(default="{'TaskID': {}, 'TaskName': {}, 'ItemID': {}, 'Time': {}, 'Payment': {}, 'State': {}}"),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='task_log',
            field=models.TextField(default="{'TaskID': {}, 'TaskName': {}, 'DataType': {}, 'ItemNum': {}, 'LastTime': {}, 'TaskState': {}}"),
        ),
    ]
