# Generated by Django 4.0.3 on 2022-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_userinfo_undetermined_alter_userinfo_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ability',
            field=models.FloatField(),
        ),
    ]
