# Generated by Django 4.0.3 on 2022-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_userinfo_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='feedback',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='feedback_file',
            field=models.TextField(default="{'TaskID': {}, 'TaskName': {}, 'State': {}, 'ProblemDescription': {}, 'ProblemType': {}, 'Priority': {}, 'ProblemDetails': {}, 'UpdatedTime': {}}"),
        ),
    ]
