# Generated by Django 4.0.3 on 2022-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_userinfo_feedback_userinfo_feedback_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='task_log',
            field=models.TextField(default="{'TaskID': {}, 'BatchID': {}, 'TaskName': {}, 'DataType': {}, 'ItemNum': {}, 'LastTime': {}, 'TaskState': {}}"),
        ),
    ]
