# Generated by Django 4.0.3 on 2022-06-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0002_templog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templabel',
            old_name='labels',
            new_name='log',
        ),
        migrations.RenameField(
            model_name='templog',
            old_name='labels',
            new_name='log',
        ),
    ]
