# Generated by Django 4.0.3 on 2022-06-09 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0012_alter_labeltasksbaseinfo_publish_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeler', '0004_templog_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempLog',
            new_name='TempSalaryLog',
        ),
        migrations.RenameField(
            model_name='templabel',
            old_name='log',
            new_name='label',
        ),
        migrations.CreateModel(
            name='TempTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.labeltasksbaseinfo')),
            ],
        ),
    ]
