# Generated by Django 4.0.3 on 2022-03-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_mysql',
        ),
    ]
