# Generated by Django 4.0.3 on 2022-03-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MysqlTest',
        ),
    ]
