# Generated by Django 4.0.3 on 2022-03-29 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTasksBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=10)),
                ('label_type', models.CharField(max_length=10)),
                ('task_deadline', models.DateTimeField()),
                ('task_payment', models.IntegerField()),
                ('rule_file', models.TextField(max_length=500)),
                ('task_difficulty', models.CharField(max_length=50)),
                ('inspect_method', models.CharField(default='cross', max_length=10)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabelTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.labeltasksbaseinfo')),
            ],
        ),
    ]
