# Generated by Django 4.0.3 on 2022-03-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTasksBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_id', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=10)),
                ('label_type', models.CharField(max_length=10)),
                ('task_deadline', models.DateTimeField()),
                ('reward', models.IntegerField()),
                ('Label_rules', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LabelTaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_data', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.labeltasksbaseinfo')),
            ],
        ),
    ]
