# Generated by Django 4.0.3 on 2022-03-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltasksbaseinfo',
            name='test',
            field=models.CharField(default='', max_length=10),
        ),
    ]
