# Generated by Django 4.0.3 on 2022-03-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_rename_label_rules_labeltasksbaseinfo_label_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeltaskdata',
            old_name='task_data',
            new_name='task_file',
        ),
        migrations.RenameField(
            model_name='labeltasksbaseinfo',
            old_name='label_rules',
            new_name='rule_file',
        ),
    ]
