# Generated by Django 4.0.3 on 2022-03-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_labeltasksbaseinfo_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeltasksbaseinfo',
            old_name='publisher',
            new_name='publishers',
        ),
    ]
