# Generated by Django 4.0.3 on 2022-03-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_rename_task_data_labeltaskdata_task_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeltasksbaseinfo',
            old_name='reward',
            new_name='task_reward',
        ),
    ]
