# Generated by Django 4.0.3 on 2022-03-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_rename_publishers_labeltasksbaseinfo_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltasksbaseinfo',
            name='test',
        ),
    ]
