# Generated by Django 4.0.3 on 2022-03-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_rename_reward_labeltasksbaseinfo_task_reward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabelTaskData',
            new_name='LabelTaskFile',
        ),
    ]
