# Generated by Django 4.0.3 on 2022-05-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_remove_labeltasksbaseinfo_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltasksbaseinfo',
            name='choices',
            field=models.CharField(default='', max_length=200),
        ),
    ]
