# Generated by Django 4.0.3 on 2022-05-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_labeltasksbaseinfo_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltasksbaseinfo',
            name='choices',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
