# Generated by Django 4.0.3 on 2022-03-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_rename_task_type_labeltasksbaseinfo_data_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeltaskfile',
            old_name='task_file',
            new_name='data_file',
        ),
        migrations.RenameField(
            model_name='labeltasksbaseinfo',
            old_name='task_reward',
            new_name='task_payment',
        ),
    ]
