# Generated by Django 4.0.3 on 2022-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_alter_labeltasksbaseinfo_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltasksbaseinfo',
            name='publish_time',
            field=models.DateTimeField(default='2022-06-03'),
        ),
    ]
