# Generated by Django 4.0.3 on 2022-06-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0012_alter_labeltasksbaseinfo_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltasksbaseinfo',
            name='batch_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labeltasksbaseinfo',
            name='total_task_id',
            field=models.IntegerField(default=0),
        ),
    ]
