# Generated by Django 4.0.3 on 2022-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0014_remove_labeltaskfile_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltaskfile',
            name='labelers',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
